version: "3.9"  # Adjusted to a more recent version of Docker Compose syntax

services:
  postgres:
    image: postgres:15  # Use a specific version of Postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-railway}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kWnSuueOZaDvqXtXsqVOZlZRGykghlFC}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  scheduler:
    build:
      context: .
      dockerfile: scheduler-dockerfile
    container_name: scheduler
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:kWnSuueOZaDvqXtXsqVOZlZRGykghlFC@postgres:5432/railway}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: on-failure

  coordinator:
    build:
      context: .
      dockerfile: coordinator-dockerfile
    container_name: coordinator
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:kWnSuueOZaDvqXtXsqVOZlZRGykghlFC@postgres:5432/railway}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: worker-dockerfile
    container_name: worker
    environment:
      WORKER_ADDRESS: worker
    depends_on:
      - coordinator
    restart: on-failure

volumes:
  postgres_data:
